### DISCUSSION TITLE
How would one style a component differently based on its neighbours while using Atomic CSS

### DISCUSSION THREAD

**Discussion by thierryk** [acss-io/atomizer#432] [Q&A] [answered]
## Question from [@chinchang](https://github.com/chinchang) 

Heres an example when using default class-based approach:

```html
<button class="btn">Hello</button>
```

When 2 buttons are required side-by-side as a group, we normally do:

```html
<div class="btn-group"
  <button class="btn">Hello</button>
  <button class="btn">Hello</button>
</div>
```

And in stylesheet we would have something like:

```css
// Removing border-radius of buttons to show they are visually grouped.
.btn-group > .btn:not(:first-child):not(:last-child) {
  border-radius: 0;
}
.btn-group > .btn:first-child {
  border-radius-top-right: 0;
  border-radius-bottom-right: 0;
}
.btn-group > .btn:last-child {
  border-radius-top-left: 0;
  border-radius-bottom-left: 0;
}
```

Now coming back to Atomic CSS, our Button component would be something like:

```html
<button class="Bgc(blue) Bdrs(4px) P(10px)">
```

To create above mentioned visual appearance of a button group, I could make a new Group component in which can wrap 2 buttons, like so:

```js
<Group>
  <Button>Hello</Button>
  <Button>World</Button>
</Group>
```

But the issue is that, since each component has its classes(styles) on itself, the Group component cannot affect the inner buttons in any way. One way I can think of is: Atomic CSS's contextual class. Using that approach the Group can add a class which the Button component can refer as a contextual class.

```html
<!-- Button -->
<button class="Bdrs(4px) Bdrs(0)__group">
```

Is this the best way to achieve my requirement?
