### ISSUE TITLE
Please add support for CSS Grid

### ISSUE THREAD

**Issue by jitendravyas** [acss-io/atomizer#294]

**Comment by src-code** [comment]
@thierryk

**Comment by thierryk** [comment]
I'm not sure this would make much sense because most grid properties take multiple values which would require to rely on the config to set these values (we can't have spaces in class names). Also, because this is mostly for page layout&mdash;not much for "modules/components"&mdash;so I think it is better to simply set those rules in a styles sheet rather than "hacking" the config. 

@src-code @renatoi What do you guys think?

**Comment by renatoi** [comment]
@thierryk makes sense to me. In any case, if we want to do this change, it would require significantly changing the parser to accept multiple params and nested parenthesis in one class:

```css
/* sometimes I think the CSSWG went nuts */
.declarations-to-support {
  display: grid;
  grid-template: repeat(4, 1fr) / 100px;
  grid-template: [header-left] "head head" 30px [header-right]
                 [main-left]   "nav  main" 1fr  [main-right]
                 [footer-left] "nav  foot" 30px [footer-right]
                 / 120px 1fr;
  grid-column-start: 5 somegridarea span;
}
```

`display:grid` is a reasonable one though.
