### ISSUE TITLE
Bdy (border-top+border-bottom) does not seem to work.

### ISSUE THREAD

**Issue by chhavi-khandelwal** [acss-io/atomizer#296]
I used following atomic classes together.
Bdy(3px)  Bdbs(s)
But this does not seem to work. Browser does not show any rule regarding width of the border.
However, Bdw works.

**Comment by thierryk** [comment]
You have a typo. It's **`BdY(3px)`**, not `Bdy(3px)`.

As a side note, the documentation contains a [whole section](https://acss.io/guides/helper-classes.html#-bd-borders-) about borders.

**Comment by tinder-rhsiao** [comment]
@thierryk I think we only have `BdY` as a helper to create 1px border
https://github.com/acss-io/atomizer/blob/master/src/helpers.js#L25-L119

`BdY(3px)` probably wont work in this case

**Comment by roderickhsiao** [comment]
@thierryk I think we only have `BdY` as a helper to create 1px border
https://github.com/acss-io/atomizer/blob/master/src/helpers.js#L25-L119

`BdY(3px)` probably wont work in this case

**Comment by chhavi-khandelwal** [comment]
It works with BdY. Thanks!

**Comment by thierryk** [comment]
cc @pankajparashar @renatoi @src-code 

Thanks @roderickhsiao. I'd copied/pasted @chhavi-khandelwal's code as-is and then simply replaced the `y` with a `Y`, leaving the extra bit :-(

As the doc shows, `BdY` does not take parameters, all helpers for borders are for a 1px border, as stated in the **Bd*** section I linked to:

> The default width of these [border] helpers is 1px as it is the most common use case. If you want to use a different width or style value, then you can either
>
>    * use standard Atomic classes, for example: `Bdw(5px) Bds(s) Bdc(#555)`

Good catch from @chhavi-khandelwal, we have typos on the [reference page](https://acss.io/reference). And it seems to be the case for most `Bd*` helpers actually (`BdX`, `BdY`, `BdT`, `BdEnd`, `BdB`, `BdStart`). I'll submit a PR.

As a side note, [Pankaj's tool](https://pankajparashar.com/atomizer-web/) shows that Atomizer plugs `Bd*` rules even if we use those classes with parameters, as in **`BdY(3px)`**. For example, `BdY(3px)` does create:

```css
.BdY {
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
  border-style: solid;
}
```

I don't think this could create problems though...

**Comment by thierryk** [comment]
Closing this and opening an issue on acss-io/**acss-site**.

**Comment by src-code** [comment]
@thierryk The problem here seems to be with the Bdy/Bdx/etc ruleset.  For rules like `Bdy` we have `allowParamToValue` set to `false`, which seems incorrect.  

Example:
```<div class="BdY Bdy(3px) BdX"></div>```

**Before:**
```css
.BdX {
  border-top-width: 0;
  border-right-width: 1px;
  border-bottom-width: 0;
  border-left-width: 1px;
}
.BdX, .BdY {
  border-style: solid;
}
.BdY {
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
}
```

**After:**

```css
.Bdy\(3px\) {
  border-top: 3px;
  border-bottom: 3px;
}
.BdX {
  border-top-width: 0;
  border-right-width: 1px;
  border-bottom-width: 0;
  border-left-width: 1px;
}
.BdX, .BdY {
  border-style: solid;
}
.BdY {
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
}
```

We don't expose helper classes in the reference tool, so searching for `BdY` will result in `Bdy` being returned since the search is case-insensitive.  Seems like we should expose helpers there to help clear up the confusion?

**Comment by src-code** [comment]
Let's re-open this, since this seems to be an atomizer ruleset issue as well as a docs issue

**Comment by thierryk** [comment]
@src-code and it seems the "matchers" are wrong in [rules.js](https://github.com/acss-io/atomizer/blob/5c207bf4b4f6d223e29409db78858ccb3375c9b4/src/rules.js#L226), isn't? So the  problem is only in this repo, the reference page using rules.js.

**Comment by thierryk** [comment]
@src-code I don't think there is a problem with `allowParamToValue` as we're not supposed to allow params there. Or am I missing something?

We should not see things like:

```css
.Bdy\(3px\) {
  border-top: 3px;
  border-bottom: 3px;
}
```

My concern was about this:

```html
<div class="Bdy(3px)"></div>
```

```css
.BdY {
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
}
```

See what I mean?
