### ISSUE TITLE
Question - `!important` on descendant

### ISSUE THREAD

**Issue by fidian** [acss-io/atomizer#343]
The code in #159 makes it so descendant classes do not rely on the namespace. This is also addressed in [your FAQ]. I can understand that reasoning, but I was wondering why an alternate approach wasn't taken. I'll use the excellent examples from the FAQ:

```html
<html id="atomic" class="open">
    ...
    <div class="open_D(b)">...</div>
</div>
```

Note that the `</div>` on the last line is from the FAQ, when it probably should be `</html>`.

```css
/* The problem you're avoiding because .open is a sibling of #atomic */
#atomic .open .open_D\(b\) {
    display: block;
}

/* The way things have been implemented */
.open .open\(Db\) {
    display: block !important;
}
```

I was wondering why this approach was decided instead of using multiple selectors for the rule?

```css
#atomic.open .open\(Db\), #atomic .open .open\(Db\) {
    display: block;
}
```

It seems to me that the above falls more in-line with the philosophy of caring about specificity, which is one of the key points of using Atomic CSS. Maybe this could be implemented or added as an option in order to prevent the use of `!important`?

[your FAQ]: https://acss.io/frequently-asked-questions.html#why-are-descendant-classes-not-relying-on-the-namespace-why-are-those-styles-using-important-
