### ISSUE TITLE
Combine h: and filter inoperative

### ISSUE THREAD

**Issue by 384400** [acss-io/atomizer#368]
Regular Css...
```css
.myClass {
    filter: brightness(0) saturate(100%) invert(96%) sepia(45%) saturate(3466%) hue-rotate(290deg) brightness(84%) contrast(126%);
}
```
works.

Atomic Css
```html
<div class="Bgi(camera) Bgr(nr) Bgz(2rem) H(2rem) W(2rem) Brightness(0):h Saturate(100%):h Invert(96%):h Sepia(45%):h Saturate(3466%):h HueRotate(290deg):h Brightness(48%):h Contrast(126%):h">
```
does not work.

Thanks.
